const methods = [
  {
    name: "exist_system_evaluate_pe_policy_implementation",
    title:
      "Existence of a national, formal, and external monitoring system to evaluate physical education policy implementation.",
    html: "<p>Monitoring is the ongoing recording and interpretation of information for the purpose of evaluation according to the agreed-upon strategic objectives or goals, anticipated outcomes (including targets), measurable indicators and a reliable information base.</p><p>For the GoPE!, the monitoring system should be implemented by an examination body or agency other than the learner’s school, under the guidance of the educational authority with responsibility for the Physical Education policy (adapted from UNESCO, 2021; UNESCO, 2013).</p><p>Some examples of monitoring systems are: school inspections, standardized tests, teacher performance assessments, and surveys for principals, teachers and students, etc.</p><p>In terms of the data collection process, the GoPE! Country Contact provides the answer and supporting evidence. Next, the GoPE! research working group will confirm the final data independently.</p><p>The data collection aimed to identify the existence of one or more monitoring systems implemented to evaluate the Physical Education policy implementation in compulsory school years that are:</p><p><strong>i) implemented on a national level,</strong></p><p><strong>ii) formal,</strong></p><p><strong>iii) ruled by an examination body under the guidance of the educational authority, and</strong></p><p><strong>iv) implemented continuously and systematically.</strong></p><p>Regarding the answer options, if a monitoring system that met all these requested criteria (a national, formal, and external monitoring system that continuously evaluates the Physical Education policy implementation) was identified, the answer was “Yes.” If no monitoring systems met all the requested criteria, the answer option was “No.”</p><p>If the answer was “Yes”, the monitoring purpose(s) had also to be identified.</p><p>A complementary search strategy involving several steps (Country's governmental and Ministry of Education websites; international reports and monitoring systems, and Google search (using the keywords “physical education” and “health and physical education” each one individually associated with “monitoring”, “surveillance”, “accountability”, “inspection”, AND with “policy”, “framework”, “plan”, “programme”, “curriculum”, AND with “Country name”) was also implemented for some countries.</p>",
  },
  {
    name: "monitoring_purpose",
    title: "Monnitoring purpose",
    html: "<p><strong>Curriculum implementation:</strong> Whether what is taught in schools follows the official national Physical Education curriculum.</p><p><strong>Mandatory Physical Education delivery:</strong> If the national policy requiring Physical Education to be mandatory is accomplished and Physical Education delivered.</p><p><strong>Minimum time accomplished:</strong> If the national policy requiring minimum Physical Education time is accomplished.</p><p><strong>Other:</strong> If there is another purpose of evaluation. If this option is selected, please indicate what is the purpose of monitoring.</p>",
  },
];
